#! /bin/bash
#
# Script to play a ding sound through your speakers.  Vastly superior to beep
# command.  Specify ding file to play in DING_FILE. Requires pulseaudio
# (paplay).

# Volume (between 0 and 100) can be an optional argument.
VOLUME=100
if [ $# -gt 0 ]
then
    VOLUME=$1
fi

# Threshold at 100.
VOLUME=$(($VOLUME<100?$VOLUME:100))

# In Linux, use paplay. Under OSX, use afplay.
if [[ $OSTYPE == *"darwin"* ]]; then
    # TODO: support volume. Note that afplay expects normal volumes in [0, 1]
    # range (approximately), but bash doesn't support floating point operations.
    afplay /System/Library/Sounds/Glass.aiff
else
    # paplay expects volume between 0 and 65536. This is our internal value.
    VOLUME_65536=$(( $VOLUME * 65536 / 100))

    DING_FILE=/usr/share/sounds/freedesktop/stereo/complete.oga

    paplay $DING_FILE --volume $VOLUME_65536 &
fi
